services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Novactive\Bundle\eZCloudinaryBundle\Twig\Extension:
        tags:
            - { name: twig.extension }

    Novactive\Bundle\eZCloudinaryBundle\Core\AliasGenerator:
        arguments:
            - "@ezpublish.fieldType.ezimage.variation_service"
            - "@ezpublish.config.resolver"
            - "@logger"
            - "%nova_ezcloudinary.authentification%"
